version: '3.4'

services:
  aksiasoftwaredeveloper.api:
    image: ${DOCKER_REGISTRY-}aksiasoftwaredeveloperapi
    build:
      context: .
      dockerfile: AksiaSoftwareDeveloper.Api/Dockerfile
  postgres:
    image: postgres:latest
    container_name: AksiaSoftware.postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: AksiaSoftware.pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pga4:/var/lib/pgadmin